-- Generated from the uploaded route. Sequence numbers are intentionally preserved.
INSERT INTO delivery_stops (sequenceNumber, address, municipality, roadLabel, status) VALUES
(1, '1342 Rosery Rd NE, Belleair Bluffs, FL', 'Belleair Bluffs', 'Rosery Rd NE', 'pending'),
(2, '239 Regina Dr S, Belleair Bluffs, FL', 'Belleair Bluffs', 'Regina Dr S', 'pending'),
(3, '220 Andrea Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Andrea Dr', 'pending'),
(4, '240 Teresa Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Teresa Dr', 'pending'),
(5, '219 Teresa Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Teresa Dr', 'pending'),
(6, '149 Regina Dr N, Belleair Bluffs, FL', 'Belleair Bluffs', 'Regina Dr N', 'pending'),
(7, '1810 Betty Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Betty Ln', 'pending'),
(8, '249 Jasper St #87, Belleair Bluffs, FL', 'Belleair Bluffs', 'Jasper St', 'pending'),
(9, '250 Rosery Rd NW #222, Belleair Bluffs, FL', 'Belleair Bluffs', 'Rosery Rd NW', 'pending'),
(10, '250 Rosery Rd NW #240, Belleair Bluffs, FL', 'Belleair Bluffs', 'Rosery Rd NW', 'pending'),
(11, '250 Rosery Rd NW #319, Belleair Bluffs, FL', 'Belleair Bluffs', 'Rosery Rd NW', 'pending'),
(12, '250 Rosery Rd NW #304, Belleair Bluffs, FL', 'Belleair Bluffs', 'Rosery Rd NW', 'pending'),
(13, '210 Beechwood Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Beechwood Ln', 'pending'),
(14, 'Largo High School, Belleair Bluffs, FL', 'Belleair Bluffs', 'Largo High School', 'pending'),
(15, '513 Poinsettia Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Poinsettia Dr', 'pending'),
(16, '509 Poinsettia Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Poinsettia Dr', 'pending'),
(17, '661 Poinsettia Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Poinsettia Dr', 'pending'),
(18, '632 Poinsettia Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Poinsettia Dr', 'pending'),
(19, '533 Parakeet Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Parakeet Ln', 'pending'),
(20, '578 Blue Bird Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Blue Bird Ln', 'pending'),
(21, '582 Blue Bird Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Blue Bird Ln', 'pending'),
(22, '466 Golden Gate Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Golden Gate Dr', 'pending'),
(23, '436 Molokai Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Molokai Ln', 'pending'),
(24, '388 Buccaneer Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Buccaneer Dr', 'pending'),
(25, '285 Lalani Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Lalani Ln', 'pending'),
(26, '1156 San Marco Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'San Marco Dr', 'pending'),
(27, '1155 San Remo Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'San Remo Dr', 'pending'),
(28, '1175 San Remo Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'San Remo Dr', 'pending'),
(29, '1185 San Remo Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'San Remo Dr', 'pending'),
(30, '1140 San Remo Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'San Remo Dr', 'pending'),
(31, '1134 San Remo Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'San Remo Dr', 'pending'),
(32, '1029 Woodbrook Dr S, Belleair Bluffs, FL', 'Belleair Bluffs', 'Woodbrook Dr S', 'pending'),
(33, '1001 Woodbrook Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Woodbrook Dr', 'pending'),
(34, '1020 Woodbrook Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Woodbrook Dr', 'pending'),
(35, '1139 Woodbrook Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Woodbrook Dr', 'pending'),
(36, '1090 7th Ave NE, Largo, FL', 'Largo', '7th Ave NE', 'pending'),
(37, '1130 6th Ave NE, Largo, FL', 'Largo', '6th Ave NE', 'pending'),
(38, '411 Tralee St, Largo, FL', 'Largo', 'Tralee St', 'pending'),
(39, '430 Cork St, Largo, FL', 'Largo', 'Cork St', 'pending'),
(40, '431 Cork St, Largo, FL', 'Largo', 'Cork St', 'pending'),
(41, '120 Central Park Dr, Largo, FL', 'Largo', 'Central Park Dr', 'pending'),
(42, '501 E Bay Dr #3302, Largo, FL', 'Largo', 'E Bay Dr', 'pending'),
(43, '1100 E Bay Dr #13, Largo, FL', 'Largo', 'E Bay Dr', 'pending'),
(44, '256 4th St NW, Largo, FL', 'Largo', '4th St NW', 'pending'),
(45, '273 4th St NW, Largo, FL', 'Largo', '4th St NW', 'pending'),
(46, '602 8th Ave NW, Largo, FL', 'Largo', '8th Ave NW', 'pending'),
(47, '622 15th Ave NW, Largo, FL', 'Largo', '15th Ave NW', 'pending'),
(48, '1025 Clearwater Largo Rd N #54, Largo, FL', 'Largo', 'Clearwater Largo Rd N', 'pending'),
(49, '1005 9th Ave NW, Largo, FL', 'Largo', '9th Ave NW', 'pending'),
(50, '816 10th St NW, Largo, FL', 'Largo', '10th St NW', 'pending'),
(51, '607 12th St NW, Largo, FL', 'Largo', '12th St NW', 'pending'),
(52, '1121 4th Ave NW, Largo, FL', 'Largo', '4th Ave NW', 'pending'),
(53, '1102 4th Ave NW, Largo, FL', 'Largo', '4th Ave NW', 'pending'),
(54, '610 11th St NW, Largo, FL', 'Largo', '11th St NW', 'pending'),
(55, '702 11th St NW, Largo, FL', 'Largo', '11th St NW', 'pending'),
(56, '715 9th St NW, Largo, FL', 'Largo', '9th St NW', 'pending'),
(57, '702 9th St NW, Largo, FL', 'Largo', '9th St NW', 'pending'),
(58, '516 10th St NW, Largo, FL', 'Largo', '10th St NW', 'pending'),
(59, '834 2nd Ave NW, Largo, FL', 'Largo', '2nd Ave NW', 'pending'),
(60, '1019 2nd Ave NW, Largo, FL', 'Largo', '2nd Ave NW', 'pending'),
(61, '192 Velma Dr W, Largo, FL', 'Largo', 'Velma Dr W', 'pending'),
(62, '292 Velma Dr W, Largo, FL', 'Largo', 'Velma Dr W', 'pending'),
(63, '316 Velma Dr W, Largo, FL', 'Largo', 'Velma Dr W', 'pending'),
(64, '1663 Velma Dr N, Largo, FL', 'Largo', 'Velma Dr N', 'pending'),
(65, '190 Tropic Blvd W, Largo, FL', 'Largo', 'Tropic Blvd W', 'pending'),
(66, '70 Tropic Blvd W, Largo, FL', 'Largo', 'Tropic Blvd W', 'pending'),
(67, '1975 W Bay Dr #107, Largo, FL', 'Largo', 'W Bay Dr', 'pending'),
(68, '1923 Sierra Cir S, Largo, FL', 'Largo', 'Sierra Cir S', 'pending'),
(69, '617 Mehlenbacher Rd, Largo, FL', 'Largo', 'Mehlenbacher Rd', 'pending'),
(70, '1606 Edna Ave NW, Largo, FL', 'Largo', 'Edna Ave NW', 'pending'),
(71, '660 15th St NW, Largo, FL', 'Largo', '15th St NW', 'pending'),
(72, '679 14th St NW, Largo, FL', 'Largo', '14th St NW', 'pending'),
(73, '667 14th St NW, Largo, FL', 'Largo', '14th St NW', 'pending'),
(74, '1204 Pine Ave NW, Largo, FL', 'Largo', 'Pine Ave NW', 'pending'),
(75, '1200 Pine Ave NW, Largo, FL', 'Largo', 'Pine Ave NW', 'pending'),
(76, '619 14th St NW, Largo, FL', 'Largo', '14th St NW', 'pending'),
(77, '607 14th St NW, Largo, FL', 'Largo', '14th St NW', 'pending'),
(78, '1316 5th Ter NW, Largo, FL', 'Largo', '5th Ter NW', 'pending'),
(79, '1306 5th Ter NW, Largo, FL', 'Largo', '5th Ter NW', 'pending'),
(80, '6 Belle Meade Cir, Largo, FL', 'Largo', 'Belle Meade Cir', 'pending'),
(81, '12 Pine Vista Dr, Largo, FL', 'Largo', 'Pine Vista Dr', 'pending'),
(82, '2268 Indian Ave N, Belleair Bluffs, FL', 'Belleair Bluffs', 'Indian Ave N', 'pending'),
(83, '2135 Victory Ave NW, Largo, FL', 'Largo', 'Victory Ave NW', 'pending'),
(84, '2162 Victory Ave NW, Largo, FL', 'Largo', 'Victory Ave NW', 'pending'),
(85, '2109 Duncan Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Duncan Dr', 'pending'),
(86, '2548 Indian Ave #B, Belleair Bluffs, FL', 'Belleair Bluffs', 'Indian Ave', 'pending'),
(87, '499 Indian Rocks Rd N, Belleair Bluffs, FL', 'Belleair Bluffs', 'Indian Rocks Rd N', 'pending'),
(88, '97 Mineola Dr E, Belleair Bluffs, FL', 'Belleair Bluffs', 'Mineola Dr E', 'pending'),
(89, '1909 Pinetree Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Pinetree Ln', 'pending'),
(90, '2170 Belmar Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Belmar Dr', 'pending'),
(91, '2293 Belmar Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Belmar Dr', 'pending'),
(92, '2255 Belmar Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Belmar Dr', 'pending'),
(93, '2083 Belmar Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Belmar Dr', 'pending'),
(94, '1840 Dolphin Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Dolphin Dr', 'pending'),
(95, '503 Rosery Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Rosery Rd', 'pending'),
(96, '1610 Pinellas Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Pinellas Rd', 'pending'),
(97, '1391 Pinellas Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Pinellas Rd', 'pending'),
(98, '1607 Pinellas Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Pinellas Rd', 'pending'),
(99, '159 Osceola Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Osceola Rd', 'pending'),
(100, '11 Fountain Sq, Belleair Bluffs, FL', 'Belleair Bluffs', 'Fountain Sq', 'pending'),
(101, '219 Osceola Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Osceola Rd', 'pending'),
(102, '222 Osceola Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Osceola Rd', 'pending'),
(103, '455 Park Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Park Ave', 'pending'),
(104, '500 Althea Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Althea Rd', 'pending'),
(105, '470 Park Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Park Ave', 'pending'),
(106, '420 Park Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Park Ave', 'pending'),
(107, '506 Osceola Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Osceola Rd', 'pending'),
(108, '511 Osceola Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Osceola Rd', 'pending'),
(109, '406 Oleander Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Oleander Rd', 'pending'),
(110, '7 Desoto Pl, Belleair Bluffs, FL', 'Belleair Bluffs', 'Desoto Pl', 'pending'),
(111, '1604 Indian Rocks Rd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Indian Rocks Rd', 'pending'),
(112, '766 Indian Rocks Rd N, Belleair Bluffs, FL', 'Belleair Bluffs', 'Indian Rocks Rd N', 'pending'),
(113, '2620 Renatta Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Renatta Dr', 'pending'),
(114, '2855 Renatta Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Renatta Dr', 'pending'),
(115, '420 Pinehurst Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Pinehurst Ave', 'pending'),
(116, '3001 Pinehurst Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Pinehurst Ave', 'pending'),
(117, '504 Cortez Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Cortez Ave', 'pending'),
(118, '784 Cortez Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Cortez Ave', 'pending'),
(119, '594 Lois Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Lois Ln', 'pending'),
(120, '2726 Bayway Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bayway Ave', 'pending'),
(121, '3089 Los Gatos Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Los Gatos Dr', 'pending'),
(122, '2747 Sunset Blvd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Sunset Blvd', 'pending'),
(123, '2880 Sunset Blvd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Sunset Blvd', 'pending'),
(124, '3054 Sunset Blvd, Belleair Bluffs, FL', 'Belleair Bluffs', 'Sunset Blvd', 'pending'),
(125, '100 Bluff View Dr #508C, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(126, '100 Bluff View Dr #403C, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(127, '100 Bluff View Dr #303A, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(128, '100 Bluff View Dr #115A, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(129, '100 Bluff View Dr #108A, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(130, '100 Bluff View Dr #103A, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(131, '155 Bluff View Dr #102, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(132, '147 Bluff View Dr #401, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(133, '139 Bluff View Dr #106, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(134, '139 Bluff View Dr #307, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(135, '131 Bluff View Dr #205, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(136, '100 Bluff View Dr #302B, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(137, '100 Bluff View Dr #205B, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(138, '100 Bluff View Dr #111B, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(139, '202 Bluff View Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(140, '508 Bluff View Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Bluff View Dr', 'pending'),
(141, '4 Sunset Bay Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Sunset Bay Dr', 'pending'),
(142, '23 Sunset Bay Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Sunset Bay Dr', 'pending'),
(143, '227 S Garden Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'S Garden Cir', 'pending'),
(144, '212 Garden Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'Garden Cir', 'pending'),
(145, '32 Winston Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Winston Dr', 'pending'),
(146, '28 Winston Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Winston Dr', 'pending'),
(147, '1737 Eagles Nest Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Eagles Nest Dr', 'pending'),
(148, '1725 Eagles Nest Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Eagles Nest Dr', 'pending'),
(149, '7 N Pine Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'N Pine Cir', 'pending'),
(150, '39 N Pine Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'N Pine Cir', 'pending'),
(151, '58 N Pine Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'N Pine Cir', 'pending'),
(152, '28 N Pine Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'N Pine Cir', 'pending'),
(153, '18 N Pine Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'N Pine Cir', 'pending'),
(154, '6 N Pine Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'N Pine Cir', 'pending'),
(155, '5 Stonegate Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Stonegate Dr', 'pending'),
(156, '1711 Peaceful Ave, Belleair Bluffs, FL', 'Belleair Bluffs', 'Peaceful Ave', 'pending'),
(157, '5 Rosery Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Rosery Ln', 'pending'),
(158, '28 Evonaire Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'Evonaire Cir', 'pending'),
(159, '30 Evonaire Cir, Belleair Bluffs, FL', 'Belleair Bluffs', 'Evonaire Cir', 'pending'),
(160, '1704 Laurie Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Laurie Ln', 'pending'),
(161, '1745 Opal Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Opal Ln', 'pending'),
(162, '780 Oakridge Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Oakridge Ln', 'pending'),
(163, '2940 W Bay Dr #204, Belleair Bluffs, FL', 'Belleair Bluffs', 'W Bay Dr', 'pending'),
(164, '2940 W Bay Dr #302, Belleair Bluffs, FL', 'Belleair Bluffs', 'W Bay Dr', 'pending'),
(165, '2940 W Bay Dr #501, Belleair Bluffs, FL', 'Belleair Bluffs', 'W Bay Dr', 'pending'),
(166, '130 Indian Rocks Rd S, Belleair Bluffs, FL', 'Belleair Bluffs', 'Indian Rocks Rd S', 'pending'),
(167, '213 Poinciana Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Poinciana Ln', 'pending'),
(168, '217 Poinciana Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Poinciana Ln', 'pending'),
(169, '113 Poinciana Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Poinciana Ln', 'pending'),
(170, '226 Driftwood Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Driftwood Ln', 'pending'),
(171, '222 Driftwood Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Driftwood Ln', 'pending'),
(172, '109 Driftwood Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Driftwood Ln', 'pending'),
(173, '506 Palm Dr, Belleair Bluffs, FL', 'Belleair Bluffs', 'Palm Dr', 'pending'),
(174, '126 Harbor View Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Harbor View Ln', 'pending'),
(175, '119 Harbor View Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Harbor View Ln', 'pending'),
(176, '104 Harbor View Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Harbor View Ln', 'pending'),
(177, '50 Harbor View Ln #15, Belleair Bluffs, FL', 'Belleair Bluffs', 'Harbor View Ln', 'pending'),
(178, '50 Harbor View Ln #27, Belleair Bluffs, FL', 'Belleair Bluffs', 'Harbor View Ln', 'pending'),
(179, '107 Palmetto Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Palmetto Ln', 'pending'),
(180, '111 Palmetto Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Palmetto Ln', 'pending'),
(181, '130 Palmetto Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Palmetto Ln', 'pending'),
(182, '217 Crestwood Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Crestwood Ln', 'pending'),
(183, '119 Crestwood Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Crestwood Ln', 'pending'),
(184, '104 Crestwood Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Crestwood Ln', 'pending'),
(185, '131 Live Oak Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Live Oak Ln', 'pending'),
(186, '203 Live Oak Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Live Oak Ln', 'pending'),
(187, '202 Live Oak Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Live Oak Ln', 'pending'),
(188, '207 Live Oak Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Live Oak Ln', 'pending'),
(189, '206 Live Oak Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Live Oak Ln', 'pending'),
(190, '211 Live Oak Ln, Belleair Bluffs, FL', 'Belleair Bluffs', 'Live Oak Ln', 'pending')
ON DUPLICATE KEY UPDATE address = VALUES(address), municipality = VALUES(municipality), roadLabel = VALUES(roadLabel);
